/**
 Generated by Eclipse
Version JAVA SE 1.7

ConnectResponseController.java : implementation file
This is a controller class for judging if the Client connect to the Server.
History:
1 Oct, 2016	--- George Heineman @1
- Created

10 Dec, 2016 --- Zhe Lyu @2
-Modify.
 */
package client.controller;

import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

import xml.Message;
import client.model.GameRoom;
import client.view.Application;


public class ConnectResponseController extends ControllerChain {
	
	public Application app;
//	public Model model;
	public GameRoom m;
	
	public ConnectResponseController(Application a, GameRoom m) {
		super();
		this.app = a;
		this.m = m;
	}
	
	@Override
	/**
	 * Get the connect id response from Server.
	 */
	public boolean process(Message response) {
	
		//System.out.println(response);
		String type = response.contents.getFirstChild().getLocalName();
		if (!type.equals ("connectResponse")) {
			return next.process(response);
		}
		Node resetGameResponse = response.contents.getFirstChild();
		NamedNodeMap map = resetGameResponse.getAttributes();
		
		String id = map.getNamedItem("id").getNodeValue();
	
		//app.getResponseArea().append(response.toString() + "\n");
		return true;
	}
}

