/**
Generated by Eclipse
Version JAVA SE 1.7

ContollerChain.java : implementation file
This is a controller class for Get the information of the global board from Server, 
 and update the local board information of  Model package.
History:
1 Oct, 2016	--- George Heineman @1
- Created.
*/
package client.controller;
import xml.Message;


public abstract class ControllerChain implements IClientController {

	/** Next one in the chain. Once null is reached, done. */
	IClientController next = null;
	
	/** Terminal entry in the chain. */
	protected ControllerChain() {
		
	}
	
	/** Chain together. */
	protected ControllerChain(ControllerChain next) {
		this.next = next;
	}
	
	/** 
	 * Carry out the processing. 
	 */
	public abstract boolean process(Message response);

}