/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

CreateGameController.java : implementation file
This is a controller class for sending request to server. 
If the client creates a game the system will make sure that the client has gotten touch with the server                  

History:

*****************************************************************/
package client.controller;


import xml.Message;
import client.model.GameRoom;
import client.view.Application;

public class CreateGameRequestController {

	Application app;
	GameRoom model;

	public CreateGameRequestController(Application app , GameRoom model) {

		this.app = app;

		this.model = model;
	}

	/** Make the request on the server and wait for response. */
	public void process() {
		// send the request to create the game.
	//	String xmlString = Message.requestHeader() + "<createGameRequest name='samplePlayer'/></request>";
		Message m = new Message (toString());
		System.out.println(m);
	//	Message m = new Message(xmlString);
		// Request the lock (this might not succeed).
		app.getServerAccess().sendRequest(m);
		
				
	}
	public String toString() {
	//	String s = model.getPlayer().getName();
		String s = model.getCurrentPlayerName();
		System.out.println(s);
		return new XmlStringBuilder("createGameRequest").add("name",s).finish()
				.toString();
		
	}
}
