/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

CreateGameController.java : implementation file
This is a controller class for sending request to server. 
If the client creates a game the system will make sure that the client has gotten touch with the server                  

History:

*****************************************************************/
package client.controller;


import xml.Message;
import client.model.Model;
import client.view.Application;

public class CreateGameController {

	Application app;
	Model model;

	public CreateGameController(Application app , Model model) {

		this.app = app;

		this.app =app;

		this.model = model;
	}

	/** Make the request on the server and wait for response. */
	public void process() {
		// send the request to create the game.
		String xmlString = Message.requestHeader() + "<createGameRequest name='samplePlayer'/></request>";
		Message m = new Message (xmlString);

		app.getServerAccess().sendRequest(m);
				
	}
}
