/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

DragControl.java : implementation file
This is a control class for handling the mouse event on the board panel

History:
7 Oct, 2016	--- Bing Zhao @1
- Created.

*****************************************************************/



package client.controller;

import java.awt.event.MouseEvent;

import javax.swing.event.MouseInputListener;


//import client.model.DrawBoardModel;
//import client.model.GameRoom;
//import client.model.Word;
import client.model.*;
import client.view.*;


public class DragControl implements MouseInputListener{
	

	private SweeperPanel panel; 
//	private DrawBoardModel drawBoardModel;
	private GameRoom model;
	private Application app;
	public DragControl(SweeperPanel panel, GameRoom m) {
		// TODO Auto-generated constructor stub
		this.panel = panel;
		this.model = m;
//		drawBoardModel = m.getDrawModel();
		
	}
	
	public void mouseDragged(MouseEvent arg0){
	    
		//drawBoardModel.addDragCellList(arg0.getPoint());
		model.getDrawModel().addDragCellList(arg0.getPoint());
		//Word word = new Word(drawBoardModel.getSelCellList2());
        panel.repaint();
	}

	public void mouseClicked(MouseEvent arg0) {
		// TODO Auto-generated method stub
		//panel.repaint();
		
	}

	public void mouseEntered(MouseEvent arg0) {
		// TODO Auto-generated method stub
		panel.repaint();
		
	}

	public void mouseExited(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void mousePressed(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
		model.getDrawModel().clearSelCellList();
		panel.repaint();
	}

	public void mouseReleased(MouseEvent arg0) {
		// TODO Auto-generated method stub
		model.getWord(model.getDrawModel().getSelCellList2());
		model.computeScore(model.getDrawModel().getSelCellList2());
		FindWordRequestController findwordrequestcontroller=new FindWordRequestController(app,model);
		findwordrequestcontroller.process();
		// sent find word request to server
		// new FindWordRequestController(app, model)
	
	}

	public void mouseMoved(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}
	

}
