/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

DragControl.java : implementation file
This is a control class for handling the mouse event on the board panel

History:
7 Oct, 2016	--- Bing Zhao @1
- Created.

*****************************************************************/



package client.controller;

import java.awt.event.MouseEvent;

import javax.swing.event.MouseInputListener;

import client.model.DrawBoardModel;
import client.view.*;


public class DragControl implements MouseInputListener{
	
	private SweeperPanel panel; 
	private DrawBoardModel model;

	
	
	// int x0 = 0;     
    // int y0 = 0; 
	
	public DragControl(SweeperPanel panel, DrawBoardModel m) {
		// TODO Auto-generated constructor stub
		this.panel = panel;
		model = m;
		
	}
	
	public void mouseDragged(MouseEvent arg0){
	      
		model.addDragCellList(arg0.getPoint());
        panel.repaint();
	}

	public void mouseClicked(MouseEvent arg0) {
		// TODO Auto-generated method stub
		//panel.repaint();
		
	}

	public void mouseEntered(MouseEvent arg0) {
		// TODO Auto-generated method stub
		panel.repaint();
		
	}

	public void mouseExited(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void mousePressed(MouseEvent arg0) {
		// TODO Auto-generated method stub
		model.clearSelCellList();
		panel.repaint();
	}

	public void mouseReleased(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void mouseMoved(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}
	

}
