/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

EmptyHandler.java : implementation file
This is a controller class for handling illegal XML response.
History:
1 Oct, 2016	--- George Heineman @1
- Created.

*****************************************************************/

package client.controller;

import xml.Message;

public final class EmptyHandler extends ControllerChain {

	@Override
/**
 * Handling illegal XML response
 */
	public boolean process(Message response) {
		System.err.println("Not Handled:" + response);
		return true;
	}

}
