/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

EmptyHandler.java : implementation file
This is a controller class for sending exit game request to the Server.
History:
1 Nov, 2016	--- Zhe Lyu @1
- Created.

*****************************************************************/
package client.controller;

import xml.Message;
import client.model.GameRoom;
import client.view.Application;
public class ExitGameRequestController {
	Application app;
	GameRoom model;

	public ExitGameRequestController(Application app , GameRoom model) {

		this.app = app;

		this.model = model;
	}

	/** 
	 * Request on the server to exit game.
	*/
	public void process() {
		// send the request to exit the game.
		//String xmlString = Message.requestHeader() + "<exitGameRequest gameId='somePlace' name='nextOne'/></request>";
		Message m = new Message (toString());

		// Request the lock (this might not succeed).
		app.getServerAccess().sendRequest(m);
		System.out.println(m);
				
	}
	/**
	 * Create XML Message of exitGameRequest.
	 */
	public String toString() {
		String s=model.getGameId();
		String s1=model.getPlayer().getName();
		return new XmlStringBuilder("exitGameRequest").add("gameId",s).add("name",s1).finish()
				.toString();
	}


}
