/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

IClientController.java : implementation file
This is an interface return TRUE if accept the response; false otherwise.                

History:
1 Oct, 2016	--- George Heineman @1
- Created.

*****************************************************************/

package client.controller;

import xml.Message;

public interface IClientController {
	
	/**
	 * Return TRUE if accept the response; false otherwise.
	 * 
	 * If unable to process a valid response, then must thrown a RuntimeException 
	 */
	public boolean process(Message response);
}
