/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

JoinGameRequestController.java : implementation file
This is a controller class for sending request to server. 
If the client requests to join a game the system will connect to server and get response.

History:
1 Oct, 2016	--- George Heineman @1
- Created.

7 Oct, 2016 --- Zhe Lyu @2
-Modify.

*****************************************************************/


package client.controller;


import xml.Message;
import client.model.GameRoom;
import client.view.Application;

public class JoinGameRequestController {

	Application app;
	GameRoom model;

	public JoinGameRequestController(Application app, GameRoom model) {
		this.app = app;
		this.model = model;
	}

	/** 
	 * Make the request on the server to join a game and wait for response. 
	 */
	public void process() {
		// send the request to create the game.
		//String xmlString = Message.requestHeader() + "<joinGameRequest gameId='somePlace' name='nextOne' password = '12345'/></request>";
		Message m = new Message (toString());
		System.out.println(m);
		// Request the lock (this might not succeed).
		app.getServerAccess().sendRequest(m);
	}
	
	/**
	 * Create XML Message joinGameRequest.
	 */
	public String toString() {
		String s = model.getGameId();
		
		String s1 = model.getCurrentPlayerName();
		return new XmlStringBuilder("joinGameRequest").add("gameId",s).add("name", s1).add("password", model.getPassword()).finish()
				.toString();
	}
}
