/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

RepositionBoardController.java : implementation file
This is a controller class for sending request to reposition board. 

7 	Nov, 2016 --- Zhe Lyu @1
-Created.

*****************************************************************/

package client.controller;

import xml.Message;
import client.model.GameRoom;
import client.view.Application;

public class RepositionBoardRequestController {
	
	Application app;
	GameRoom model;
	
	public RepositionBoardRequestController (Application app , GameRoom model) {

		this.app = app;

		this.model = model;
	}

	/** Make the request on the server to left move the local board and wait for response. */
	public void leftProcess() {

		//String xmlString = Message.requestHeader() + "<repositionBoardRequest gameId='somePlace' name='nextOne' rowChange='-1' /></request>";
		Message m = new Message (ltoString());
		System.out.println(m);
		app.getServerAccess().sendRequest(m);
	
	}
	/** Make the request on the server to right move the local board and wait for response. */
    public void rightProcess() {
		
    	//String xmlString = Message.requestHeader() + "<repositionBoardRequest gameId='somePlace' name='nextOne' rowChange='1' /></request>";
		Message m = new Message (rtoString());
		System.out.println(m);
		app.getServerAccess().sendRequest(m);
	
	}
    /** Make the request on the server to up move the local board and wait for response. */
    public void upProcess() {
		
		//String xmlString = Message.requestHeader() + "<repositionBoardRequest gameId='somePlace' name='nextOne' colChange='1'/></request>";
		Message m = new Message (utoString());
		System.out.println(m);
		app.getServerAccess().sendRequest(m);
	
	}
    /** Make the request on the server to down move the local board and wait for response. */
    public void downProcess() {
		
		//String xmlString = Message.requestHeader() + "<repositionBoardRequest gameId='somePlace'  name='nextOne' colChange='-1' /></request>";
		Message m = new Message (dtoString());
		System.out.println(m);
		app.getServerAccess().sendRequest(m);
	
	}
    /**
     * Create XML Message to up move
     */
    public String utoString() {
    	String s1 = model.getGameId();
		String s = model.getCurrentPlayerName();
		return new XmlStringBuilder("repositionBoardRequest").add("gameId", s1).add("name",s).add("rowChange","-1").add("colChange", "0").finish()
				.toString();
    }
    /**
     * Create XML Message to down move
     */
    public String dtoString() {
    	String s1 = model.getGameId();
		String s = model.getCurrentPlayerName();
		return new XmlStringBuilder("repositionBoardRequest").add("gameId", s1).add("name",s).add("rowChange","1").add("colChange", "0").finish()
				.toString();
    }
    /**
     * Create XML Message to left move
     */
    public String ltoString() {
    	String s1 = model.getGameId();
		String s = model.getCurrentPlayerName();
		return new XmlStringBuilder("repositionBoardRequest").add("gameId", s1).add("name",s).add("rowChange","0").add("colChange","-1").finish()
				.toString();
    }
    /**
     * Create XML Message to right move
     */
    public String rtoString() {
    	String s1 = model.getGameId();
		String s = model.getCurrentPlayerName();
		return new XmlStringBuilder("repositionBoardRequest").add("gameId", s1).add("name",s).add("rowChange","0").add("colChange","1").finish()
				.toString();
    }
}
