/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

ResetGameResponseController.java : implementation file
This is a controller class to send a request to reset game

7 	Nov, 2016 --- Zhe Lyu @1
-Created.

*****************************************************************/
package client.controller;

import xml.Message;
import client.model.GameRoom;
import client.view.Application;

public class ResetGameRequestController {
	
	Application app;
	GameRoom model;
	
	public ResetGameRequestController(Application app, GameRoom model){
		
		this.app = app;
		this.model = model;
	}
	/** 
	 * Make the request to reset game on the server and wait for response. 
	 */
	public void process(){
		
		//String gameId = map.getNamedItem("gameId").getNodeValue();
		
		// send the request to reset the game.
		//String xmlString = Message.requestHeader() + "<resetGameRequest gameId='somePlace' /></request>";
		Message m = new Message (toString());
		System.out.println(m);
		app.getServerAccess().sendRequest(m);
		
	}
	/**
	 * Create the XML Message: resetGameRequest
	 */
	public String toString() {
		String s=model.getGameId();
		return new XmlStringBuilder("resetGameRequest").add("gameId",s).finish()
				.toString();
	}

}
