/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

BoardDisplay.java : implementation file
This is a view class for creating the game board page.

History:
7 Oct, 2016	--- Bing Zhao @1
- Created.

*****************************************************************/



package client.view;

import java.awt.BorderLayout;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

import client.controller.*;
import client.model.GameRoom;


import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Window.Type;

public class BoardDisplay extends JFrame {
	
	 
	 GameRoom model;
     Application app;
     
     SweeperPanel sweeperPanel;
     
    
     private JButton btnLeft;
     private JButton btnRight;
     private JButton btnUp;
     private JButton btnDown;
     private JButton btnLock;
     private JButton btnReset;
     private JButton btnExit;
     private JPanel panel;
	
	/**
	 * Create the frame.
	 */
	public BoardDisplay(final Application app, final GameRoom m) {
		
		
		this.model = m;
		this.app = app;
		
		//setSize(1024, 768);
		setBounds(0, 0, 1024, 768);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		
		panel = new JPanel();
		panel.setBounds(0, 0, 1024, 768);
		
		
		sweeperPanel = new SweeperPanel(m.getDrawModel());
		sweeperPanel.setBounds(0, 0, 600, 700);
	
		btnLeft = new JButton("LEFT");
		btnLeft.setBounds(809, 33, 150, 63);
		btnLeft.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.lprocess();
			}
		});
		
		btnRight = new JButton("RIGHT");
		btnRight.setBounds(809, 129, 150, 63);
		btnRight.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.rprocess();
			}
		});
		
		btnUp = new JButton("UP");
		btnUp.setBounds(809, 225, 150, 63);
		btnUp.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.uprocess();
			}
		});
		
		btnDown = new JButton("DOWN");
		btnDown.setBounds(809, 321, 150, 63);
		btnDown.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.dprocess();
			}
		});
		
		btnLock = new JButton("LOCK");
		btnLock.setBounds(809, 417, 150, 63);
		btnLock.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				LockGameController lock=new LockGameController(app,m);
				lock.process();
			}
		});
		
		
		btnReset = new JButton("RESET");
		btnReset.setBounds(809, 513, 150, 63);
		btnReset.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				ResetGameController reset=new ResetGameController(app,m);
				reset.process();
			}
		});
		
		btnExit = new JButton("EXIT");
		btnExit.setBounds(809, 609, 150, 63);
		btnExit.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				ExitGameController reset=new ExitGameController(app,m);
				reset.process();
			}
		});
		
	
		
		
		getContentPane().setLayout(null);  
	
    	getContentPane().add(sweeperPanel);
		getContentPane().add(btnLeft);
		getContentPane().add(btnRight);
		getContentPane().add(btnUp);
		getContentPane().add(btnDown);
		getContentPane().add(btnLock);
		getContentPane().add(btnReset);
		getContentPane().add(btnExit);
		getContentPane().add(panel);
		
		setVisible(true);
			         
	}
}
