/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

BoardDisplay.java : implementation file
This is a view class for creating the game board page.

History:
7 Oct, 2016	--- Bing Zhao @1
- Created.

*****************************************************************/



package client.view;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

import client.controller.*;
import client.model.GameRoom;


import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class BoardDisplay extends JFrame {
	
	 
	 GameRoom model;
     Application app;
     
     SweeperPanel sweeperPanel;
     
     JPanel buttons;
     private JButton btnLeft;
     private JButton btnRight;
     private JButton btnUp;
     private JButton btnDown;
     private JButton btnLock;
     private JButton btnReset;
	
	/**
	 * Create the frame.
	 */
	public BoardDisplay(final Application app, final GameRoom m) {
		//getContentPane().setBackground(Color.YELLOW);
		setBounds(100, 100, 1079, 458);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.model = m;
		this.app = app;
		sweeperPanel = new SweeperPanel(m.getDrawModel());
		buttons = new JPanel();
		
		btnLeft = new JButton("LEFT");
		btnLeft.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.process();
			}
		});
		
		btnRight = new JButton("RIGHT");
		btnRight.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.process();
			}
		});
		
		btnUp = new JButton("UP");
		btnUp.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.process();
			}
		});
		
		btnDown = new JButton("DOWN");
		btnDown.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				RepositionController reposition=new RepositionController(app,m);
				reposition.process();
			}
		});
		
		btnLock = new JButton("LOCK");
		btnLock.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				LockGameController reposition=new LockGameController(app,m);
				reposition.process();
			}
		});
		
		
		btnReset = new JButton("RESET");
		btnReset.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				ResetGameController reset=new ResetGameController(app,m);
				reset.process();
			}
		});
		
		JButton btnExit = new JButton("EXIT");
		btnExit.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				ExitGameController reset=new ExitGameController(app,m);
				reset.process();
			}
		});
		
		
		
	//	GroupLayout gl_sweeperPanel = new GroupLayout(sweeperPanel);
		GroupLayout gl_buttons = new GroupLayout(buttons);
		gl_buttons.setHorizontalGroup(
			gl_buttons.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_buttons.createSequentialGroup()
					.addContainerGap()
					.addComponent(btnReset, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnLock, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnLeft)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnRight, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnUp, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(btnDown, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnExit, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		gl_buttons.setVerticalGroup(
			gl_buttons.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_buttons.createSequentialGroup()
					.addContainerGap(253, Short.MAX_VALUE)
					.addGroup(gl_buttons.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnReset)
						.addComponent(btnLock)
						.addComponent(btnLeft)
						.addComponent(btnRight)
						.addComponent(btnUp)
						.addComponent(btnDown)
						.addComponent(btnExit))
					.addGap(41))
		);
		gl_buttons.linkSize(SwingConstants.HORIZONTAL, new Component[] {btnLeft, btnRight, btnUp, btnDown, btnLock});
		buttons.setLayout(gl_buttons);

		
    	getContentPane().add(sweeperPanel, BorderLayout.CENTER);
	
		getContentPane().add(buttons, BorderLayout.SOUTH);
	
		pack();
		         
	}
}
