/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

GameRoom.java : implementation file
This is a model class for future use. It records information related
to a game room. It includes password, locked info, the board and 
players playing the game.  

History:
7 Oct, 2016	--- Zeling Lei @1
- Created.

*****************************************************************/
package client.model;

import java.util.*;

public class GameRoom {
	
 // practice model or team model
	private boolean locked; 
	private List<Player> players; 
	private String password; 
	private Board board;
	
	public GameRoom(List<Player> players, String password) {
		
		this.password = password;
		this.players = new ArrayList<Player>();
		for (int i = 0; i < players.size(); i++) {
			this.players.add(players.get(i));
		}
	}
	
	// Returns the managing player
	public Player getManagingPlayer() {
		
		return null;
	}
	
	// Calculates scores for each player
	public int computeScore(Word word) {
		
		return 0;
	}
	
	// Updates the board
	public void updateBoard(Board board, List<Player> players) {
		
		
	}
}
