/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

Player.java : implementation file
This is a model class for store player message and get the player's 
position from server.

History:
5 Oct, 2016	--- Zhe Lyu @1
- Created.

*****************************************************************/


package client.model;

import java.util.*;

public class Player {
	
	private Boolean isManger;
	
	private String gameId;
	private int score;
	private String name;
	private Position position;
	private List<String> words;
	private Board board;
 
	public Player(String gameId, String name, String score, Board board, Position position) {
		
		this.gameId = gameId;
		this.name = name; 
		this.board = board;
		this.position = position;
		

	}
	
	/** Get the player's position from server*/
	public Position getPosition() {
		
		return position; 
	}

}
