/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

Player.java : implementation file
This is a model class for store player message and get the player's position from server.

History:
5 Oct, 2016	--- Zhe Lyu @1
- Created.

*****************************************************************/


package client.model;

import java.util.*;

public class Player {
	
	private Boolean isManger;
	private String nickName;
	private String id;
	private int totalScore;
	private Position position;
	private List<String> words;
 
	public void Player(Boolean isManger, String nickName, String id){
	
		this.isManger = isManger;
		this.nickName = nickName;
		this.id = id;
	}
	
	/** Get the player's position from server*/
	public void getPosition(Position position) {
		
		
	}

}
