/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

Player.java : implementation file
This is a model class for store player message and get the player's 
position from server.

History:
5 Oct, 2016	--- Zhe Lyu @1
- Created.

*****************************************************************/


package client.model;

import java.util.*;

public class Player {
	
	private boolean isManager;
	private long score;
	private Position position;
	private List<String> words;
	private Board board;
	private String name; 
 
	public Player(String name, String score, String sixteenLetter, Position position, boolean isManager) {
		
		
		this.name = name; 
		this.board = new Board(sixteenLetter);
		this.position = position;
		this.isManager = isManager; 
		
	}
	
	/** Get the player's position from server*/
	public Position getPosition() {
		
		return position; 
	}
	
	
	public String getName() {
		
		return name; 
	}
	
	public long getScore() {
		
		return score; 
	}
	
	public Board getBoard() {
		return board;
	}
	
}
