/***************************************************************
Generated by Eclipse
Version JAVA SE 1.7

Position.java : implementation file
This is a model class. It records the column and row number, and 
implements hashCode and equal method used for realizing hashMap

History:
7 Oct, 2016	--- Zeling Lei @1
- Created.

*****************************************************************/

package client.model;

// This class stores the position info in a board

public class Position {
	
	
	private int column;
	private int row;
	
	// Constructs Position using column and row
    public Position(int column, int row){
    	
    	this.column = column;
    	this.row = row;
    }
    
    // Used to implement Map<Position, Cell> in Board.java
    public int hashCode() {
    	
    	return ((Integer)row).hashCode() * 11 + ((Integer)column).hashCode(); 
    }
    
    // Used to implement Map<Position, Cell> in Board.java
    public boolean equals(Object o) {
    	
    	if (o instanceof Position) {
    		
    		Position other = (Position) o;
    		return column == other.column && row == other.row;
    		
    	} else {
    		
    		return false;
    	}
    }  
    
    // used for test only
    public String toString() {
    	
    	return "[" + column + ",  " + row + "]";
    	
    }

	public int getColumn() {
		return column;
	}

	public void setColumn(int column) {
		this.column = column;
	}

	public int getRow() {
		return row;
	}

	public void setRow(int row) {
		this.row = row;
	}
    
    
	
}
